# Generated by Django 5.2.7 on 2025-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
