# Generated by Django 5.2.7 on 2025-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['title', 'name']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('dumbbells', 'Dumbbells'), ('bodyweight', 'Bodyweight'), ('machine', 'Machine'), ('kettlebells', 'Kettlebells'), ('stretches', 'Stretches'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='female_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='female_videos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='force',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='grips',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='has_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='male_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='male_videos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
